/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Alarm {
    #[serde(rename = "alarmId")]
    pub alarm_id: uuid::Uuid,
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "alarmTypeId")]
    pub alarm_type_id: uuid::Uuid,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "sendCall")]
    pub send_call: bool,
    #[serde(rename = "sendSms")]
    pub send_sms: bool,
    #[serde(rename = "sendApp")]
    pub send_app: bool,
    #[serde(rename = "guidance")]
    pub guidance: models::AlarmGuidance,
    #[serde(rename = "triggerTime")]
    pub trigger_time: String,
    #[serde(rename = "triggerName")]
    pub trigger_name: String,
    #[serde(rename = "triggerAccountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_account_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "cancellationTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancellation_time: Option<Option<String>>,
    #[serde(rename = "cancellationAccountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancellation_account_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl Alarm {
    pub fn new(alarm_id: uuid::Uuid, tenant_id: uuid::Uuid, alarm_type_id: uuid::Uuid, label: String, send_call: bool, send_sms: bool, send_app: bool, guidance: models::AlarmGuidance, trigger_time: String, trigger_name: String, last_change: String) -> Alarm {
        Alarm {
            alarm_id,
            tenant_id,
            alarm_type_id,
            label,
            send_call,
            send_sms,
            send_app,
            guidance,
            trigger_time,
            trigger_name,
            trigger_account_id: None,
            cancellation_time: None,
            cancellation_account_id: None,
            last_change,
        }
    }
}

