/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlarmConfirmation {
    #[serde(rename = "OFF_SITE")]
    OFFSITE,
    #[serde(rename = "EVACUATED")]
    EVACUATED,
    #[serde(rename = "SAFE_SPOT")]
    SAFESPOT,

}

impl ToString for AlarmConfirmation {
    fn to_string(&self) -> String {
        match self {
            Self::OFFSITE => String::from("OFF_SITE"),
            Self::EVACUATED => String::from("EVACUATED"),
            Self::SAFESPOT => String::from("SAFE_SPOT"),
        }
    }
}

impl Default for AlarmConfirmation {
    fn default() -> AlarmConfirmation {
        Self::OFFSITE
    }
}




