/*
 * Alarm Backend
 *
 * # API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.  For most endpoints, the caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. If your interacting with this API using the Swagger interface, you need to set the JWT token by clicking on the **Authorize** button on the right side of the header. As the value don't forget that the Authorization header starts with the fixed value `Bearer` followed by a space followed by the actual JWT token value.  If anything is unclear or you found a bug in the documentation, please contact <tech@p7m.de>. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Alarm {
    #[serde(rename = "alarmId")]
    pub alarm_id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "alarmTypeId")]
    pub alarm_type_id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "sendCall")]
    pub send_call: bool,
    #[serde(rename = "sendSms")]
    pub send_sms: bool,
    #[serde(rename = "sendApp")]
    pub send_app: bool,
    #[serde(rename = "guidance")]
    pub guidance: Guidance,
    #[serde(rename = "triggerTime")]
    pub trigger_time: String,
    #[serde(rename = "triggerAccountId", skip_serializing_if = "Option::is_none")]
    pub trigger_account_id: Option<String>,
    #[serde(rename = "cancellationTime", skip_serializing_if = "Option::is_none")]
    pub cancellation_time: Option<String>,
    #[serde(rename = "cancellationAccountId", skip_serializing_if = "Option::is_none")]
    pub cancellation_account_id: Option<String>,
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl Alarm {
    pub fn new(alarm_id: String, tenant_id: String, alarm_type_id: String, label: String, send_call: bool, send_sms: bool, send_app: bool, guidance: Guidance, trigger_time: String, last_change: String) -> Alarm {
        Alarm {
            alarm_id,
            tenant_id,
            alarm_type_id,
            label,
            send_call,
            send_sms,
            send_app,
            guidance,
            trigger_time,
            trigger_account_id: None,
            cancellation_time: None,
            cancellation_account_id: None,
            last_change,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Guidance {
    #[serde(rename = "EVACUATE")]
    EVACUATE,
    #[serde(rename = "GO_TO_SAFE_PLACE")]
    GOTOSAFEPLACE,
}

impl Default for Guidance {
    fn default() -> Guidance {
        Self::EVACUATE
    }
}

