/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlarmConfirmation {
    #[serde(rename = "OFF_SITE")]
    OffSite,
    #[serde(rename = "EVACUATED")]
    Evacuated,
    #[serde(rename = "SAFE_SPOT")]
    SafeSpot,

}

impl std::fmt::Display for AlarmConfirmation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OffSite => write!(f, "OFF_SITE"),
            Self::Evacuated => write!(f, "EVACUATED"),
            Self::SafeSpot => write!(f, "SAFE_SPOT"),
        }
    }
}

impl Default for AlarmConfirmation {
    fn default() -> AlarmConfirmation {
        Self::OffSite
    }
}

