/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AlarmData {
    #[serde(rename = "data")]
    pub data: Vec<crate::models::Alarm>,
}

impl AlarmData {
    pub fn new(data: Vec<crate::models::Alarm>) -> AlarmData {
        AlarmData {
            data,
        }
    }
}


