/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlarmMedium {
    #[serde(rename = "CALL")]
    CALL,
    #[serde(rename = "SMS")]
    SMS,
    #[serde(rename = "APP")]
    APP,

}

impl ToString for AlarmMedium {
    fn to_string(&self) -> String {
        match self {
            Self::CALL => String::from("CALL"),
            Self::SMS => String::from("SMS"),
            Self::APP => String::from("APP"),
        }
    }
}

impl Default for AlarmMedium {
    fn default() -> AlarmMedium {
        Self::CALL
    }
}




