/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AlarmGuidance {
    #[serde(rename = "EVACUATE")]
    Evacuate,
    #[serde(rename = "GO_TO_SAFE_PLACE")]
    GoToSafePlace,

}

impl std::fmt::Display for AlarmGuidance {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Evacuate => write!(f, "EVACUATE"),
            Self::GoToSafePlace => write!(f, "GO_TO_SAFE_PLACE"),
        }
    }
}

impl Default for AlarmGuidance {
    fn default() -> AlarmGuidance {
        Self::Evacuate
    }
}

