/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperAlarm {
    #[serde(rename = "data")]
    pub data: Vec<models::ListWrapperAlarmDataInner>,
}

impl ListWrapperAlarm {
    pub fn new(data: Vec<models::ListWrapperAlarmDataInner>) -> ListWrapperAlarm {
        ListWrapperAlarm {
            data,
        }
    }
}

