/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperAlarmRecipient {
    #[serde(rename = "data")]
    pub data: Vec<models::ListWrapperAlarmRecipientDataInner>,
}

impl ListWrapperAlarmRecipient {
    pub fn new(data: Vec<models::ListWrapperAlarmRecipientDataInner>) -> ListWrapperAlarmRecipient {
        ListWrapperAlarmRecipient {
            data,
        }
    }
}

