/*
 * Alarm Backend
 *
 * ## API for generating and tracking alarms  This is the API of what P7M mainly uses within the Telfas service.
 *
 * The version of the OpenAPI document: 0.2.1
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewAlarmRecipient {
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "medium")]
    pub medium: crate::models::AlarmMedium,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "submissionTime", skip_serializing_if = "Option::is_none")]
    pub submission_time: Option<String>,
    #[serde(rename = "deliveryTime", skip_serializing_if = "Option::is_none")]
    pub delivery_time: Option<String>,
    #[serde(rename = "confirmation", skip_serializing_if = "Option::is_none")]
    pub confirmation: Option<Box<crate::models::AlarmConfirmation>>,
    #[serde(rename = "confirmationTime", skip_serializing_if = "Option::is_none")]
    pub confirmation_time: Option<String>,
}

impl NewAlarmRecipient {
    pub fn new(account_id: String, medium: crate::models::AlarmMedium, address: String) -> NewAlarmRecipient {
        NewAlarmRecipient {
            account_id,
            medium,
            address,
            submission_time: None,
            delivery_time: None,
            confirmation: None,
            confirmation_time: None,
        }
    }
}


